//
//  CommonContextSDK.h
//  context
//
//  Created by Waldemar Krumrick on 9/10/13.
//  Copyright (c) 2013 Intel. All rights reserved.
//

#import <Foundation/Foundation.h>

#define SuppressPerformSelectorLeakWarning(Stuff) \
do { \
_Pragma("clang diagnostic push") \
_Pragma("clang diagnostic ignored \"-Warc-performSelector-leaks\"") \
Stuff; \
_Pragma("clang diagnostic pop") \
} while (0)

//CONTEXT ERROR CONSTANTS
FOUNDATION_EXPORT int CONTEXT_NOT_INIT;
FOUNDATION_EXPORT int CONTEXT_ERROR_PARAMETER;
FOUNDATION_EXPORT int CONTEXT_INTERNAL_ERROR;
FOUNDATION_EXPORT int CONTEXT_INTERNAL_WARNING;

//URNS
FOUNDATION_EXPORT NSString *URN_LOCATION_CURRENT;
FOUNDATION_EXPORT NSString *URN_BATTERY_TYPE;
FOUNDATION_EXPORT NSString *URN_MUSIC_TYPE;
FOUNDATION_EXPORT NSString *URN_CALL_TYPE;
FOUNDATION_EXPORT NSString *URN_CONTACTS_TYPE;
FOUNDATION_EXPORT NSString *URN_INSTALLED_APPS_TYPE;
FOUNDATION_EXPORT NSString *URN_CURRENT_APPS_TYPE;
FOUNDATION_EXPORT NSString *URN_CALENDAR_TYPE;
FOUNDATION_EXPORT NSString *URN_NETWORK_TYPE;
FOUNDATION_EXPORT NSString *URN_MESSAGES_TYPE;
FOUNDATION_EXPORT NSString *URN_DEVICE_INFORMATION_TYPE;

//OPTIONS KEYS
FOUNDATION_EXPORT NSString *OPTION_HARVESTER_MODE;
FOUNDATION_EXPORT NSString *OPTION_MAX_APP_QUANTITY;
FOUNDATION_EXPORT NSString *OPTION_MONITOR_INTERVAL;
FOUNDATION_EXPORT NSString *OPTION_INSTALLED_APPS_FILTER; //Filter by user applications or system applications (default: user & system applications)

//OPTIONS VALUES
FOUNDATION_EXPORT NSString *SERVICE_CONTACT_LOW_DETAILS;
FOUNDATION_EXPORT NSString *SERVICE_CONTACT_MEDIUM_DETAILS;
FOUNDATION_EXPORT NSString *SERVICE_CONTACT_HIGH_DETAILS;
FOUNDATION_EXPORT NSString *SERVICE_CONTACT_FULL_DETAILS; //Default
FOUNDATION_EXPORT NSString *SERVICE_INSTALLED_APPS_USER_APPLICATIONS;
FOUNDATION_EXPORT NSString *SERVICE_INSTALLED_APPS_SYSTEM_APPLICATIONS;
FOUNDATION_EXPORT NSString *SERVICE_INSTALLED_APPS_ALL_APPLICATIONS;

//ACTION STATES
enum ACTION_STATE {
    ACTION_STATE_UPDATE
};

@interface CommonContextSDK : NSObject

+ (NSMutableDictionary *)getCallHistory;

+ (void)putCallHistory:(NSString *)callNumber;

@end
